# Generated by OracleGuard
# Automated Test Oracle Generation

def test_find_max_0():
    # Setup
    from example import *
    import unittest
    from unittest.mock import Mock, patch
    from typing import *
    arg_numbers = [1, 2, 3]
    mock_ValueError = Mock()

    # Execute
    result = find_max(arg_numbers)

    # Assert
    assert result == 3  # Checks that the function correctly identifies the maximum value in the input list [1, 2, 3].
    assert isinstance(result, int)  # Ensures the return type is an integer as specified in the function signature and documentation.
    with unittest.TestCase().assertRaises(ValueError): find_max([])  # Verifies that the function raises a ValueError when called with an empty list, testing exception handling for boundary condition.

def test_find_max_1():
    # Setup
    from example import *
    import unittest
    from unittest.mock import Mock, patch
    from typing import *
    arg_numbers = [1, 2, 3]
    mock_ValueError = Mock()

    # Execute
    result = find_max(arg_numbers)

    # Assert
    assert result == 3  # Ensures the function correctly returns the maximum value from the input list [1, 2, 3].
    assert isinstance(result, int)  # Validates that the returned value is of type int as expected.
    assert find_max([5]) == 5  # Checks boundary condition where the list contains only one element, the function should return that element.
    try:
    find_max([])
    assert False, 'Expected ValueError not raised'
except ValueError:
    pass  # Verifies that the function raises a ValueError when called with an empty list, as specified in the documentation.

def test_calculate_discount_0():
    # Setup
    from example import *
    import unittest
    from unittest.mock import Mock, patch
    from typing import *
    arg_price = 34.52
    arg_discount_percent = 42.38
    mock_ValueError = Mock()

    # Execute
    result = calculate_discount(arg_price, arg_discount_percent)

    # Assert
    assert isinstance(result, float)  # Ensures the return type is float as expected from the function signature.
    assert result == round(arg_price - (arg_price * (arg_discount_percent / 100)), 2)  # Validates that the returned price is correctly calculated with the given discount and rounded to 2 decimal places.
    assert 0 <= result <= arg_price  # Checks that the discounted price is never negative and never exceeds the original price.

def test_calculate_discount_1():
    # Setup
    from example import *
    import unittest
    from unittest.mock import Mock, patch
    from typing import *
    arg_price = 34.52
    arg_discount_percent = 42.38
    mock_ValueError = Mock()

    # Execute
    result = calculate_discount(arg_price, arg_discount_percent)

    # Assert
    assert isinstance(result, float)  # The function should return a float representing the discounted price.
    assert result == round(arg_price - (arg_price * (arg_discount_percent / 100)), 2)  # The returned discounted price should be correctly calculated and rounded to 2 decimal places.
    assert 0 <= result <= arg_price  # The discounted price should never be negative or greater than the original price.
    try:
    calculate_discount(arg_price, -1)
except ValueError as e:
    assert str(e) == 'Discount must be between 0 and 100'
else:
    assert False, 'ValueError not raised for negative discount_percent'  # The function should raise a ValueError if the discount percentage is less than 0.

def test_factorial_0():
    # Setup
    from example import *
    import unittest
    from unittest.mock import Mock, patch
    from typing import *
    arg_n = 66
    mock_ValueError = Mock()

    # Execute
    result = factorial(arg_n)

    # Assert
    assert isinstance(result, int)  # The factorial function should return an integer value.
    assert result == 5.443449390774431e+92  # The factorial of 66 is a known value and the function should return the correct factorial.
    with unittest.TestCase().assertRaises(ValueError): factorial(-1)  # The function should raise a ValueError for negative inputs, as per the specification.
    assert factorial(0) == 1 and factorial(1) == 1  # Factorial of 0 and 1 should both return 1, testing boundary conditions.

def test_factorial_1():
    # Setup
    from example import *
    import unittest
    from unittest.mock import Mock, patch
    from typing import *
    arg_n = 66
    mock_ValueError = Mock()

    # Execute
    result = factorial(arg_n)

    # Assert
    assert isinstance(result, int)  # The return value should be of type int as factorial returns an integer.
    assert result == 523022617466601111760007224100074291200000000  # The factorial of 66 must be correctly calculated as 66! (precomputed value).
    with unittest.TestCase().assertRaises(ValueError): factorial(-1)  # Factorial should raise ValueError when called with a negative integer input.

def test_fibonacci_1():
    # Setup
    from example import *
    import unittest
    from unittest.mock import Mock, patch
    from typing import *
    arg_n = 63
    mock_fib_append = Mock()

    # Execute
    result = fibonacci(arg_n)

    # Assert
    assert isinstance(result, list)  # The function should return a list as specified in the return type and documentation.
    assert len(result) == arg_n  # The returned list should contain exactly n terms, verifying the function generates the correct sequence length.
    assert result[:5] == [0, 1, 1, 2, 3]  # The first five Fibonacci numbers are a well-known sequence and should be correct to verify the sequence generation logic.
    assert all(isinstance(x, int) for x in result)  # All elements in the Fibonacci sequence should be integers, ensuring type consistency within the returned list.

def test_divide_0():
    # Setup
    from example import *
    import unittest
    from unittest.mock import Mock, patch
    from typing import *
    obj = TestClass()
    arg_a = 43.64
    arg_b = 63.16
    mock_ZeroDivisionError = Mock()
    mock_self_history_append = Mock()

    # Execute
    result = obj.divide(arg_a, arg_b)

    # Assert
    assert isinstance(result, float)  # Ensures that the return type of the divide function is a float as specified in the signature.
    assert abs(result - (arg_a / arg_b)) < 1e-9  # Verifies that the returned result is the correct division of the two input floats within a small tolerance to handle floating point precision.
    assert obj.history[-1] == f"{arg_a} / {arg_b} = {result}"  # Checks that the side effect of appending the correct division operation string to the history list occurs as expected.

def test_divide_1():
    # Setup
    from example import *
    import unittest
    from unittest.mock import Mock, patch
    from typing import *
    obj = TestClass()
    arg_a = 43.64
    arg_b = 63.16
    mock_ZeroDivisionError = Mock()
    mock_self_history_append = Mock()

    # Execute
    result = obj.divide(arg_a, arg_b)

    # Assert
    assert abs(result - (arg_a / arg_b)) < 1e-9  # Checks that the returned result is the correct division of a by b within floating point tolerance.
    assert isinstance(result, float)  # Ensures the return type is float as specified in the function signature.
    assert obj.history[-1] == f"{arg_a} / {arg_b} = {result}"  # Verifies that the division operation and result are correctly appended to the object's history attribute as a side effect.
    try:
    obj.divide(arg_a, 0)
    assert False, "Expected ZeroDivisionError"
except ZeroDivisionError:
    pass  # Confirms that dividing by zero raises the expected ZeroDivisionError exception.

