"""
Stage 3: LLM Assertion Generation
Uses Large Language Models to generate candidate assertions for test oracles.
Supports multiple LLM providers: OpenAI, Anthropic, local models.
"""

import json
import os
from typing import List, Dict, Any, Optional
from dataclasses import dataclass
from abc import ABC, abstractmethod


@dataclass
class CandidateAssertion:
    """A candidate assertion generated by LLM"""
    assertion_code: str
    explanation: str
    confidence: float  # 0.0 to 1.0
    oracle_type: str   # 'value', 'state', 'exception', 'property'
    metadata: Dict[str, Any]


@dataclass
class TestCase:
    """Complete test case with prefix and assertions"""
    test_name: str
    prefix_code: str
    method_call: str
    assertions: List[CandidateAssertion]
    full_test_code: str


class LLMProvider(ABC):
    """Abstract base class for LLM providers"""
    
    @abstractmethod
    def generate_assertions(self, prompt: str) -> str:
        """Generate assertions given a prompt"""
        pass


class OpenAIProvider(LLMProvider):
    """OpenAI GPT provider"""
    
    def __init__(self, api_key: Optional[str] = None, model: str = "gpt-4"):
        self.api_key = api_key or os.getenv("OPENAI_API_KEY")
        self.model = model or "gpt-4.1-mini"
        
        if not self.api_key:
            raise ValueError("OpenAI API key not found. Set OPENAI_API_KEY environment variable.")
    
    def generate_assertions(self, prompt: str) -> str:
        """Call OpenAI API"""
        print("DEBUG model =", self.model)
        try:
            import openai
            
            client = openai.OpenAI(api_key=self.api_key)
            
            response = client.chat.completions.create(
                model=self.model,
                messages=[
                    {"role": "system", "content": "You are an expert software testing engineer."},
                    {"role": "user", "content": prompt}
                ],
                temperature=0.7,
                max_tokens=1000
            )
            
            return response.choices[0].message.content
            
        except ImportError:
            raise ImportError("Please install openai: pip install openai")
        except Exception as e:
            raise RuntimeError(f"OpenAI API error: {e}")


class AnthropicProvider(LLMProvider):
    """Anthropic Claude provider"""
    
    def __init__(self, api_key: Optional[str] = None, model: str = "claude-sonnet-4-5-20250929"):
        self.api_key = api_key or os.getenv("ANTHROPIC_API_KEY")
        self.model = model
        
        if not self.api_key:
            raise ValueError("Anthropic API key not found. Set ANTHROPIC_API_KEY environment variable.")
    
    def generate_assertions(self, prompt: str) -> str:
        """Call Anthropic API"""
        try:
            import anthropic
            
            client = anthropic.Anthropic(api_key=self.api_key)
            
            response = client.messages.create(
                model=self.model,
                max_tokens=1000,
                messages=[
                    {"role": "user", "content": prompt}
                ]
            )
            
            return response.content[0].text
            
        except ImportError:
            raise ImportError("Please install anthropic: pip install anthropic")
        except Exception as e:
            raise RuntimeError(f"Anthropic API error: {e}")


class MockLLMProvider(LLMProvider):
    """Mock provider for testing without API calls"""
    
    def generate_assertions(self, prompt: str) -> str:
        """Return mock assertions"""
        return """
{
  "assertions": [
    {
      "code": "assert result is not None",
      "explanation": "The function should return a non-null value",
      "confidence": 0.9,
      "type": "value"
    },
    {
      "code": "assert isinstance(result, int)",
      "explanation": "Based on the return type annotation, result should be an integer",
      "confidence": 0.95,
      "type": "value"
    }
  ]
}
"""


class AssertionGenerator:
    """Main assertion generation engine"""
    
    def __init__(self, provider: LLMProvider, metadata, prefix):
        """
        Args:
            provider: LLM provider instance
            metadata: MUTMetadata from Stage 1
            prefix: TestPrefix from Stage 2
        """
        self.provider = provider
        self.metadata = metadata
        self.prefix = prefix
    
    def generate_test_cases(self, count: int = 3) -> List[TestCase]:
        """Generate multiple test cases with assertions"""
        test_cases = []
        
        for i in range(count):
            prompt = self._build_prompt(i)
            response = self.provider.generate_assertions(prompt)
            
            assertions = self._parse_llm_response(response)
            test_case = self._build_test_case(i, assertions)
            
            test_cases.append(test_case)
        
        return test_cases
    
    def _build_prompt(self, test_index: int) -> str:
        """Construct prompt for LLM"""
        
        # Build method call
        args = [f"arg_{p.name}" for p in self.metadata.parameters if p.name != 'self']
        method_call = f"{self.metadata.name}({', '.join(args)})"
        
        prompt = f"""You are a software testing expert. Generate test assertions for the following Python function.

**Function Signature:**
```python
{self.metadata.signature}
```

**Function Documentation:**
{self.metadata.docstring or 'No documentation provided.'}

**Function Source Code:**
```python
{self.metadata.source_code}
```

**Test Setup (Prefix):**
```python
{self.prefix.setup_code}
```

**Method Call:**
```python
result = {method_call}
```

**Task:**
Generate 2-4 appropriate assertions for this test case. Consider:
1. Return value correctness (based on inputs and expected behavior)
2. Type validation
3. Boundary conditions
4. Side effects or state changes
5. Exception handling (if applicable)

**Output Format (JSON):**
{{
  "assertions": [
    {{
      "code": "assert <condition>",
      "explanation": "<why this assertion is important>",
      "confidence": <0.0 to 1.0>,
      "type": "<value|state|exception|property>"
    }}
  ]
}}

Provide ONLY the JSON response, no additional text.
"""
        return prompt
    
    def _parse_llm_response(self, response: str) -> List[CandidateAssertion]:
        """Parse LLM response into structured assertions"""
        
        # Clean response (remove markdown code blocks if present)
        response = response.strip()
        if response.startswith("```json"):
            response = response[7:]
        if response.startswith("```"):
            response = response[3:]
        if response.endswith("```"):
            response = response[:-3]
        response = response.strip()
        
        try:
            data = json.loads(response)
            assertions = []
            
            for item in data.get('assertions', []):
                assertion = CandidateAssertion(
                    assertion_code=item.get('code', ''),
                    explanation=item.get('explanation', ''),
                    confidence=float(item.get('confidence', 0.5)),
                    oracle_type=item.get('type', 'value'),
                    metadata={}
                )
                assertions.append(assertion)
            
            return assertions
            
        except json.JSONDecodeError as e:
            print(f"Warning: Failed to parse LLM response as JSON: {e}")
            # Fallback: try to extract assertions from text
            return self._fallback_parse(response)
    
    def _fallback_parse(self, response: str) -> List[CandidateAssertion]:
        """Fallback parser for non-JSON responses"""
        assertions = []
        lines = response.split('\n')
        
        for line in lines:
            line = line.strip()
            if line.startswith('assert '):
                assertion = CandidateAssertion(
                    assertion_code=line,
                    explanation="Extracted from text response",
                    confidence=0.5,
                    oracle_type='value',
                    metadata={}
                )
                assertions.append(assertion)
        
        return assertions
    
    def _build_test_case(self, index: int, assertions: List[CandidateAssertion]) -> TestCase:
        """Construct complete test case"""
        
        # Build method call
        args = [f"arg_{p.name}" for p in self.metadata.parameters if p.name != 'self']
        
        if self.prefix.fixture_objects:
            # Instance method call
            obj = self.prefix.fixture_objects[0]
            method_call = f"result = {obj}.{self.metadata.name}({', '.join(args)})"
        else:
            # Function call
            method_call = f"result = {self.metadata.name}({', '.join(args)})"
        
        # Build full test code
        test_name = f"test_{self.metadata.name}_{index}"
        
        test_code_parts = [
            f"def {test_name}():",
            "    # Setup",
        ]
        
        for line in self.prefix.setup_code.split('\n'):
            if line.strip():
                test_code_parts.append(f"    {line}")
        
        test_code_parts.append("")
        test_code_parts.append("    # Execute")
        test_code_parts.append(f"    {method_call}")
        test_code_parts.append("")
        test_code_parts.append("    # Assert")
        
        for assertion in assertions:
            test_code_parts.append(f"    {assertion.assertion_code}  # {assertion.explanation}")
        
        full_test_code = '\n'.join(test_code_parts)
        
        return TestCase(
            test_name=test_name,
            prefix_code=self.prefix.setup_code,
            method_call=method_call,
            assertions=assertions,
            full_test_code=full_test_code
        )


# --- CLI for testing Stage 3 ---
def main():
    import argparse
    import sys
    from stage_1_static_analysis import StaticAnalyzer
    from stage_2_prefix_generation import PrefixGenerator
    
    parser = argparse.ArgumentParser(description="Stage 3: LLM Assertion Generation")
    parser.add_argument("file", help="Source file to analyze")
    parser.add_argument("--method", help="Specific method name")
    parser.add_argument("--provider", choices=['openai', 'anthropic', 'mock'], 
                       default='mock', help="LLM provider")
    parser.add_argument("--count", type=int, default=2, help="Number of test cases")
    parser.add_argument("--output", help="Output file for generated tests")
    
    args = parser.parse_args()
    
    try:
        # Stage 1: Analyze
        print("[Stage 1] Analyzing source code...")
        methods = StaticAnalyzer.analyze(args.file)
        
        if args.method:
            methods = [m for m in methods if m.name == args.method]
        
        if not methods:
            print("No methods found!")
            sys.exit(1)
        
        # Select LLM provider
        if args.provider == 'openai':
            provider = OpenAIProvider()
        elif args.provider == 'anthropic':
            provider = AnthropicProvider()
        else:
            provider = MockLLMProvider()
            print("[Info] Using mock LLM provider (no API calls)")
        
        all_test_cases = []
        
        for method in methods:
            print(f"\n[Stage 2] Generating test prefix for '{method.name}'...")
            
            # Stage 2: Generate prefix
            prefix_gen = PrefixGenerator(method, args.file)
            prefix = prefix_gen.generate()
            
            print(f"[Stage 3] Generating assertions using {args.provider}...")
            
            # Stage 3: Generate assertions
            assertion_gen = AssertionGenerator(provider, method, prefix)
            test_cases = assertion_gen.generate_test_cases(count=args.count)
            
            all_test_cases.extend(test_cases)
            
            # Display results
            print(f"\n{'='*60}")
            print(f"Generated {len(test_cases)} test cases for '{method.name}'")
            print(f"{'='*60}\n")
            
            for tc in test_cases:
                print(tc.full_test_code)
                print(f"\n# Assertions: {len(tc.assertions)}")
                for a in tc.assertions:
                    print(f"#   - {a.assertion_code} (confidence: {a.confidence})")
                print()
        
        # Write to file if specified
        if args.output:
            with open(args.output, 'w') as f:
                f.write("# Generated Test Cases\n")
                f.write("# Generated by OracleGuard Stage 3\n\n")
                
                for tc in all_test_cases:
                    f.write(tc.full_test_code)
                    f.write("\n\n")
            
            print(f"\n[+] Test cases written to {args.output}")
    
    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        import traceback
        traceback.print_exc()
        sys.exit(1)


if __name__ == "__main__":
    main()