#!/usr/bin/env python3
"""
OracleGuard — Unified CLI entry point.

Usage:
    uv run main.py <source.py> [options]

Examples:
    uv run main.py example.py
    uv run main.py example.py --method calculate_discount --llm openai
    uv run main.py example.py --strategy boundary --mutants 20
    uv run main.py example.py --output verified_tests.py --json
"""

import argparse
import json
import sys

from oracleguard import OracleGuard, PipelineConfig, PipelineResult, OracleStatus


def print_report(results: list[PipelineResult]) -> None:
    """Print a human-readable summary report."""
    print("\n" + "=" * 70)
    print("FINAL REPORT")
    print("=" * 70)

    icons = {
        OracleStatus.VERIFIED: "[OK]",
        OracleStatus.SUSPICIOUS: "[??]",
        OracleStatus.NEEDS_REFINEMENT: "[FIX]",
        OracleStatus.REJECTED: "[FAIL]",
    }

    for r in results:
        icon = icons.get(r.verdict.status, "[?]")
        print(f"\n{icon} {r.method.name} / {r.test_case.test_name}")
        print(f"     Status: {r.verdict.status.value}")
        print(f"     Trust:  {r.verdict.trust_score:.2f}")
        print(f"     Assertions: {len(r.test_case.assertions)}")
        for w in r.verdict.weaknesses:
            print(f"     - {w}")

    verified = sum(1 for r in results if r.verdict.status == OracleStatus.VERIFIED)
    print(f"\nSummary: {verified}/{len(results)} oracles verified\n")


def main() -> None:
    parser = argparse.ArgumentParser(
        prog="oracleguard",
        description="OracleGuard: Trust-Scored LLM-Based Test Oracle Generation",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""\
Examples:
  uv run main.py example.py
  uv run main.py example.py --method calculate_discount --llm openai
  uv run main.py example.py --strategy boundary --mutants 20
  uv run main.py example.py --output verified_tests.py --json
""",
    )

    parser.add_argument("file", help="Python source file to analyze")
    parser.add_argument("--method", help="Analyze only this method")

    llm = parser.add_argument_group("LLM options")
    llm.add_argument("--llm", choices=["openai", "mock"],
                     default="mock",
                     help="LLM provider (default: mock). 'openai' works with "
                          "OpenAI, OpenRouter, or any compatible API.")
    llm.add_argument("--model", help="Model name (default: gpt-4)")
    llm.add_argument("--base-url", help="API base URL (e.g. https://openrouter.ai/api/v1)")
    llm.add_argument("--call-interval", type=float, default=0.0,
                     help="Min seconds between API calls (rate limiter)")

    pipeline = parser.add_argument_group("Pipeline options")
    pipeline.add_argument("--mutants", type=int, default=10,
                          help="Number of mutants per test case (default: 10)")
    pipeline.add_argument("--tests", type=int, default=2,
                          help="Test cases per method (default: 2)")
    pipeline.add_argument("--strategy",
                          choices=["random", "boundary", "equivalence"],
                          default="random",
                          help="Input generation strategy (default: random)")
    pipeline.add_argument("--min-complexity", type=int, default=2)
    pipeline.add_argument("--max-complexity", type=int, default=20)

    output = parser.add_argument_group("Output options")
    output.add_argument("--output", help="Write verified tests to this file")
    output.add_argument("--json", action="store_true",
                        help="Print results as JSON")
    output.add_argument("--verbose", action="store_true")

    args = parser.parse_args()

    config = PipelineConfig(
        llm_provider=args.llm,
        llm_model=args.model,
        llm_base_url=args.base_url,
        call_interval=args.call_interval,
        num_mutants=args.mutants,
        test_count=args.tests,
        min_complexity=args.min_complexity,
        max_complexity=args.max_complexity,
        prefix_strategy=args.strategy,
        verbose=args.verbose,
    )

    try:
        guard = OracleGuard(config)
        results = guard.run(args.file, args.method)

        if not results:
            print("No results produced.")
            sys.exit(1)

        print_report(results)

        if args.output:
            with open(args.output, "w") as f:
                f.write("# Generated by OracleGuard\n\n")
                for r in results:
                    if r.verdict.status == OracleStatus.VERIFIED:
                        f.write(r.test_case.full_test_code + "\n\n")
            print(f"Verified tests written to {args.output}\n")

        if args.json:
            print(json.dumps([
                {
                    "method": r.method.name,
                    "test": r.test_case.test_name,
                    "status": r.verdict.status.value,
                    "trust_score": round(r.verdict.trust_score, 4),
                    "weaknesses": r.verdict.weaknesses,
                    "recommendations": r.verdict.recommendations,
                }
                for r in results
            ], indent=2))

    except KeyboardInterrupt:
        print("\nInterrupted.")
        sys.exit(130)
    except Exception as e:
        print(f"\nError: {e}", file=sys.stderr)
        if args.verbose:
            import traceback
            traceback.print_exc()
        sys.exit(1)


if __name__ == "__main__":
    main()
