"""
Stage 3: LLM Assertion Generation
Uses Large Language Models to generate candidate assertions for test oracles.
Supports any OpenAI-compatible API (OpenAI, OpenRouter, local servers).
"""

import json
import os
import time
from typing import List, Dict, Any, Optional
from dataclasses import dataclass
from abc import ABC, abstractmethod

from oracleguard.static_analysis import MUTMetadata
from oracleguard.prefix_generation import TestPrefix


@dataclass
class CandidateAssertion:
    """A candidate assertion generated by an LLM."""
    assertion_code: str
    explanation: str
    confidence: float  # 0.0 to 1.0
    oracle_type: str   # 'value', 'state', 'exception', 'property'
    metadata: Dict[str, Any]


@dataclass
class TestCase:
    """Complete test case with prefix and assertions."""
    test_name: str
    prefix_code: str
    method_call: str
    assertions: List[CandidateAssertion]
    full_test_code: str


# ---------------------------------------------------------------------------
# LLM Providers
# ---------------------------------------------------------------------------

class LLMProvider(ABC):
    """Abstract base class for LLM providers."""

    @abstractmethod
    def generate_assertions(self, prompt: str) -> str:
        """Send prompt to the LLM and return raw text response."""
        ...


class OpenAIProvider(LLMProvider):
    """OpenAI-compatible provider with built-in rate limiting.

    Works with OpenAI, OpenRouter, and any OpenAI-compatible API by
    setting base_url. Includes exponential backoff for rate limits.
    """

    def __init__(self, api_key: Optional[str] = None,
                 model: str = "gpt-4",
                 base_url: Optional[str] = None,
                 max_retries: int = 5,
                 call_interval: float = 0.0):
        """
        Args:
            api_key: API key. Falls back to OPENAI_API_KEY or OPENROUTER_API_KEY.
            model: Model identifier.
            base_url: API base URL. None = OpenAI default. Set to
                      "https://openrouter.ai/api/v1" for OpenRouter.
            max_retries: Max retry attempts on rate limit or transient errors.
            call_interval: Min seconds between API calls (rate limiter).
        """
        self.api_key = api_key or os.getenv("OPENAI_API_KEY") or os.getenv("OPENROUTER_API_KEY")
        self.model = model
        self.base_url = base_url
        self.max_retries = max_retries
        self.call_interval = call_interval
        self._last_call = 0.0
        if not self.api_key:
            raise ValueError(
                "API key not found. Set OPENAI_API_KEY or OPENROUTER_API_KEY."
            )

    def generate_assertions(self, prompt: str) -> str:
        import openai

        # Rate limiter
        if self.call_interval > 0:
            elapsed = time.time() - self._last_call
            if elapsed < self.call_interval:
                time.sleep(self.call_interval - elapsed)

        kwargs = {"api_key": self.api_key}
        if self.base_url:
            kwargs["base_url"] = self.base_url

        client = openai.OpenAI(**kwargs)

        # Use user-only message for max compatibility (some models
        # don't support system role).
        full_prompt = (
            "You are an expert software testing engineer.\n\n" + prompt
        )

        for attempt in range(self.max_retries):
            try:
                response = client.chat.completions.create(
                    model=self.model,
                    messages=[{"role": "user", "content": full_prompt}],
                    temperature=0.7,
                    max_tokens=1000,
                )
                self._last_call = time.time()
                content = response.choices[0].message.content
                if content:
                    return content
            except Exception as e:
                err_str = str(e)
                is_rate_limit = '429' in err_str or 'rate' in err_str.lower()
                if is_rate_limit:
                    delay = 3.0 * (2 ** attempt)
                    print(f"    Rate limited, waiting {delay:.0f}s...")
                    time.sleep(delay)
                    continue
                print(f"    API error (attempt {attempt+1}): {err_str[:150]}")
                if attempt < self.max_retries - 1:
                    time.sleep(2.0)
                    continue
                raise

        raise RuntimeError(f"Failed after {self.max_retries} retries")


class MockLLMProvider(LLMProvider):
    """Mock provider for offline testing without API calls."""

    def generate_assertions(self, prompt: str) -> str:
        return json.dumps({
            "assertions": [
                {
                    "code": "assert result is not None",
                    "explanation": "The function should return a non-null value",
                    "confidence": 0.9,
                    "type": "value"
                },
                {
                    "code": "assert isinstance(result, (int, float))",
                    "explanation": "Result should be numeric based on return type",
                    "confidence": 0.95,
                    "type": "value"
                }
            ]
        })


# ---------------------------------------------------------------------------
# Assertion Generator
# ---------------------------------------------------------------------------

class AssertionGenerator:
    """Generates test assertions using an LLM provider."""

    def __init__(self, provider: LLMProvider, metadata: MUTMetadata,
                 prefix: TestPrefix):
        self.provider = provider
        self.metadata = metadata
        self.prefix = prefix

    def generate_test_cases(self, count: int = 3) -> List[TestCase]:
        """Generate multiple test cases with assertions."""
        return [self._generate_one(i) for i in range(count)]

    def _generate_one(self, index: int) -> TestCase:
        prompt = self._build_prompt()
        response = self.provider.generate_assertions(prompt)
        assertions = self._parse_response(response)
        return self._build_test_case(index, assertions)

    def _build_prompt(self) -> str:
        args = [f"arg_{p.name}" for p in self.metadata.parameters if p.name != 'self']
        call = f"{self.metadata.name}({', '.join(args)})"
        return f"""You are a software testing expert. Generate test assertions for the following Python function.

**Function Signature:**
```python
{self.metadata.signature}
```

**Function Documentation:**
{self.metadata.docstring or 'No documentation provided.'}

**Function Source Code:**
```python
{self.metadata.source_code}
```

**Test Setup (Prefix):**
```python
{self.prefix.setup_code}
```

**Method Call:**
```python
result = {call}
```

**Task:**
Generate 2-4 appropriate assertions. Consider:
1. Return value correctness
2. Type validation
3. Boundary conditions
4. Side effects or state changes
5. Exception handling (if applicable)

**Output Format (JSON):**
{{
  "assertions": [
    {{
      "code": "assert <condition>",
      "explanation": "<why this assertion is important>",
      "confidence": <0.0 to 1.0>,
      "type": "<value|state|exception|property>"
    }}
  ]
}}

Provide ONLY the JSON response, no additional text.
"""

    def _parse_response(self, response: str) -> List[CandidateAssertion]:
        """Parse LLM response into structured assertions."""
        text = response.strip()
        for prefix in ("```json", "```"):
            if text.startswith(prefix):
                text = text[len(prefix):]
        if text.endswith("```"):
            text = text[:-3]
        text = text.strip()

        try:
            data = json.loads(text)
            return [
                CandidateAssertion(
                    assertion_code=item.get('code', ''),
                    explanation=item.get('explanation', ''),
                    confidence=float(item.get('confidence', 0.5)),
                    oracle_type=item.get('type', 'value'),
                    metadata={},
                )
                for item in data.get('assertions', [])
            ]
        except json.JSONDecodeError:
            return self._fallback_parse(text)

    def _fallback_parse(self, text: str) -> List[CandidateAssertion]:
        return [
            CandidateAssertion(
                assertion_code=line.strip(),
                explanation="Extracted from text response",
                confidence=0.5,
                oracle_type='value',
                metadata={},
            )
            for line in text.split('\n')
            if line.strip().startswith('assert ')
        ]

    def _build_test_case(self, index: int, assertions: List[CandidateAssertion]) -> TestCase:
        args = [f"arg_{p.name}" for p in self.metadata.parameters if p.name != 'self']
        if self.prefix.fixture_objects:
            obj = self.prefix.fixture_objects[0]
            method_call = f"result = {obj}.{self.metadata.name}({', '.join(args)})"
        else:
            method_call = f"result = {self.metadata.name}({', '.join(args)})"

        test_name = f"test_{self.metadata.name}_{index}"

        # Split setup into module-level imports and function-level code.
        # `import *` is only valid at module level.
        module_imports = []
        func_setup = []
        for line in self.prefix.setup_code.split('\n'):
            stripped = line.strip()
            if not stripped:
                continue
            if stripped.startswith(('import ', 'from ')):
                module_imports.append(line)
            else:
                func_setup.append(line)

        lines = list(module_imports)
        lines.append("")
        lines.append(f"def {test_name}():")
        lines.append("    # Setup")
        for line in func_setup:
            lines.append(f"    {line}")
        lines += ["", "    # Execute", f"    {method_call}", "", "    # Assert"]
        for a in assertions:
            lines.append(f"    {a.assertion_code}  # {a.explanation}")

        return TestCase(
            test_name=test_name,
            prefix_code=self.prefix.setup_code,
            method_call=method_call,
            assertions=assertions,
            full_test_code='\n'.join(lines),
        )
