"""
Stage 3: LLM Assertion Generation
Uses Large Language Models to generate candidate assertions for test oracles.
"""

import json
import os
from typing import List, Dict, Any, Optional
from dataclasses import dataclass
from abc import ABC, abstractmethod

from oracleguard.static_analysis import MUTMetadata
from oracleguard.prefix_generation import TestPrefix


@dataclass
class CandidateAssertion:
    """A candidate assertion generated by an LLM."""
    assertion_code: str
    explanation: str
    confidence: float  # 0.0 to 1.0
    oracle_type: str   # 'value', 'state', 'exception', 'property'
    metadata: Dict[str, Any]


@dataclass
class TestCase:
    """Complete test case with prefix and assertions."""
    test_name: str
    prefix_code: str
    method_call: str
    assertions: List[CandidateAssertion]
    full_test_code: str


# ---------------------------------------------------------------------------
# LLM Providers
# ---------------------------------------------------------------------------

class LLMProvider(ABC):
    """Abstract base class for LLM providers."""

    @abstractmethod
    def generate_assertions(self, prompt: str) -> str:
        """Send prompt to the LLM and return raw text response."""
        ...


class OpenAIProvider(LLMProvider):
    """OpenAI GPT provider."""

    def __init__(self, api_key: Optional[str] = None, model: str = "gpt-4"):
        self.api_key = api_key or os.getenv("OPENAI_API_KEY")
        self.model = model or "gpt-4"
        if not self.api_key:
            raise ValueError("OpenAI API key not found. Set OPENAI_API_KEY.")

    def generate_assertions(self, prompt: str) -> str:
        import openai
        client = openai.OpenAI(api_key=self.api_key)
        response = client.chat.completions.create(
            model=self.model,
            messages=[
                {"role": "system", "content": "You are an expert software testing engineer."},
                {"role": "user", "content": prompt}
            ],
            temperature=0.7,
            max_tokens=1000,
        )
        return response.choices[0].message.content


class AnthropicProvider(LLMProvider):
    """Anthropic Claude provider."""

    def __init__(self, api_key: Optional[str] = None,
                 model: str = "claude-sonnet-4-5-20250929"):
        self.api_key = api_key or os.getenv("ANTHROPIC_API_KEY")
        self.model = model
        if not self.api_key:
            raise ValueError("Anthropic API key not found. Set ANTHROPIC_API_KEY.")

    def generate_assertions(self, prompt: str) -> str:
        import anthropic
        client = anthropic.Anthropic(api_key=self.api_key)
        response = client.messages.create(
            model=self.model,
            max_tokens=1000,
            messages=[{"role": "user", "content": prompt}],
        )
        return response.content[0].text


class MockLLMProvider(LLMProvider):
    """Mock provider for offline testing without API calls."""

    def generate_assertions(self, prompt: str) -> str:
        return json.dumps({
            "assertions": [
                {
                    "code": "assert result is not None",
                    "explanation": "The function should return a non-null value",
                    "confidence": 0.9,
                    "type": "value"
                },
                {
                    "code": "assert isinstance(result, (int, float))",
                    "explanation": "Result should be numeric based on return type",
                    "confidence": 0.95,
                    "type": "value"
                }
            ]
        })


# ---------------------------------------------------------------------------
# Assertion Generator
# ---------------------------------------------------------------------------

class AssertionGenerator:
    """Generates test assertions using an LLM provider."""

    def __init__(self, provider: LLMProvider, metadata: MUTMetadata,
                 prefix: TestPrefix):
        self.provider = provider
        self.metadata = metadata
        self.prefix = prefix

    def generate_test_cases(self, count: int = 3) -> List[TestCase]:
        """Generate multiple test cases with assertions."""
        return [self._generate_one(i) for i in range(count)]

    def _generate_one(self, index: int) -> TestCase:
        prompt = self._build_prompt()
        response = self.provider.generate_assertions(prompt)
        assertions = self._parse_response(response)
        return self._build_test_case(index, assertions)

    def _build_prompt(self) -> str:
        args = [f"arg_{p.name}" for p in self.metadata.parameters if p.name != 'self']
        call = f"{self.metadata.name}({', '.join(args)})"
        return f"""You are a software testing expert. Generate test assertions for the following Python function.

**Function Signature:**
```python
{self.metadata.signature}
```

**Function Documentation:**
{self.metadata.docstring or 'No documentation provided.'}

**Function Source Code:**
```python
{self.metadata.source_code}
```

**Test Setup (Prefix):**
```python
{self.prefix.setup_code}
```

**Method Call:**
```python
result = {call}
```

**Task:**
Generate 2-4 appropriate assertions. Consider:
1. Return value correctness
2. Type validation
3. Boundary conditions
4. Side effects or state changes
5. Exception handling (if applicable)

**Output Format (JSON):**
{{
  "assertions": [
    {{
      "code": "assert <condition>",
      "explanation": "<why this assertion is important>",
      "confidence": <0.0 to 1.0>,
      "type": "<value|state|exception|property>"
    }}
  ]
}}

Provide ONLY the JSON response, no additional text.
"""

    def _parse_response(self, response: str) -> List[CandidateAssertion]:
        """Parse LLM response into structured assertions."""
        text = response.strip()
        for prefix in ("```json", "```"):
            if text.startswith(prefix):
                text = text[len(prefix):]
        if text.endswith("```"):
            text = text[:-3]
        text = text.strip()

        try:
            data = json.loads(text)
            return [
                CandidateAssertion(
                    assertion_code=item.get('code', ''),
                    explanation=item.get('explanation', ''),
                    confidence=float(item.get('confidence', 0.5)),
                    oracle_type=item.get('type', 'value'),
                    metadata={},
                )
                for item in data.get('assertions', [])
            ]
        except json.JSONDecodeError:
            return self._fallback_parse(text)

    def _fallback_parse(self, text: str) -> List[CandidateAssertion]:
        return [
            CandidateAssertion(
                assertion_code=line.strip(),
                explanation="Extracted from text response",
                confidence=0.5,
                oracle_type='value',
                metadata={},
            )
            for line in text.split('\n')
            if line.strip().startswith('assert ')
        ]

    def _build_test_case(self, index: int, assertions: List[CandidateAssertion]) -> TestCase:
        args = [f"arg_{p.name}" for p in self.metadata.parameters if p.name != 'self']
        if self.prefix.fixture_objects:
            obj = self.prefix.fixture_objects[0]
            method_call = f"result = {obj}.{self.metadata.name}({', '.join(args)})"
        else:
            method_call = f"result = {self.metadata.name}({', '.join(args)})"

        test_name = f"test_{self.metadata.name}_{index}"
        lines = [f"def {test_name}():", "    # Setup"]
        for line in self.prefix.setup_code.split('\n'):
            if line.strip():
                lines.append(f"    {line}")
        lines += ["", "    # Execute", f"    {method_call}", "", "    # Assert"]
        for a in assertions:
            lines.append(f"    {a.assertion_code}  # {a.explanation}")

        return TestCase(
            test_name=test_name,
            prefix_code=self.prefix.setup_code,
            method_call=method_call,
            assertions=assertions,
            full_test_code='\n'.join(lines),
        )
